---
- name: Install prerequisite packages for building CMake
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - gcc
    - gcc-c++
    - make
    - wget
    - openssl-devel

- name: Download CMake source
  get_url:
    url: https://github.com/Kitware/CMake/releases/download/v3.22.2/cmake-3.22.2.tar.gz
    dest: /tmp/cmake.tar.gz

- name: Extract CMake source
  unarchive:
    src: /tmp/cmake.tar.gz
    dest: /opt/cmake
    remote_src: yes

- name: Build and install CMake
  command: >
    cmake --prefix=/usr/local
    -- ./configure
    --prefix=/usr/local
    && make -j $(nproc)
    && make install
  args:
    chdir: /opt/cmake
